# Generated by Django 2.2.6 on 2020-04-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anshaj', '0006_auto_20200417_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='job_category',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
