# Generated by Django 2.2.6 on 2020-04-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anshaj', '0007_job_post_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='immediate',
            field=models.BooleanField(default=False),
        ),
    ]
