# Generated by Django 2.2.6 on 2020-04-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anshaj', '0008_job_post_immediate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_post',
            name='immediate',
        ),
        migrations.AlterField(
            model_name='job_post',
            name='datetime',
            field=models.DateField(null=True),
        ),
    ]
