# Generated by Django 2.2.6 on 2020-04-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anshaj', '0009_auto_20200418_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview_attended_datas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('candidates_givenname', models.CharField(max_length=200)),
                ('candidates_surename', models.CharField(max_length=200)),
                ('candidates_email', models.EmailField(max_length=254)),
                ('candidates_phonenumber', models.BigIntegerField()),
            ],
        ),
    ]
